name: node
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/node.yml"
      - "app/node/**"
  pull_request:
    paths:
      - ".github/workflows/node.yml"
      - "app/node/**"
  workflow_dispatch:
defaults:
  run:
    working-directory: app/node

jobs:
  node:
    name: node test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - uses: bahmutov/npm-install@v1
        with:
          working-directory: app/node

      - name: type check
        run: |
          yarn type-check

      - name: eslint
        run: |
          yarn lint

      - name: prettier
        run: |
          yarn format

      - name: unit test
        run: |
          yarn test
